version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: your-database
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: postgres
      DB_USER: your-username
      DB_PASSWORD: your-password
      DB_DATABASE: your-database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
